name: Linter

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: golangci
        uses: TykTechnologies/github-actions/.github/workflows/golangci.yaml@main
      - name: sonarcloud
        uses: TykTechnologies/github-actions/.github/workflows/sonarcloud.yaml@main
        with:
          exclusions: ""
        secrets: inherit
